# v2 syntax
version: '2'

# Named volumes
volumes:
  test-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: test-mysql
    volumes:
      - test-mysql-data:/var/lib/mysql
    ports:
      - "33061:3306"
    networks:
      dev-network:
        ipv4_address: 10.5.0.10
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.3-nginx
    container_name: test-app
    volumes:
      - .:/var/www/app
    ports:
      - "8081:8080"
    networks:
      dev-network:
        ipv4_address: 10.5.0.11
    links:
      - mysql

networks: 
  dev-network:
    driver: bridge
    ipam: 
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
